
export const RESIZE_CANVAS = 'RESIZE_CANVAS';
export const TOGGLE_SMOOTHING = 'TOGGLE_SMOOTHING';
export const RESET_PLOT = 'RESET';
export const START_ZOOM_SELECTION = 'START_ZOOM_SELECTION';
export const MOVE_ZOOM_SELECTION = 'MOVE_ZOOM_SELECTION';
export const FINISH_ZOOM_SELECTION = 'FINISH_ZOOM_SELECTION';
export const CANCEL_ZOOM = 'CANCEL_ZOOM';
